### ISSUE TITLE
Cannot find module 'node:module'

### ISSUE THREAD

**Issue by Tianyeeeeee** [unjs/mlly#113]
###Problem: Cannot find module 'node:module'
Source code:

```Js language

const node_ module=require（'node:module'）；// Why is "Node: xxx" added here

```

When I was building the project, I received an error "Cannot find module 'node:module'".

In my project (Vue3), I used "unplugin vue components" and "unplugin auto import".

How to solve it?

**Comment by ymxiang1125** [comment]
+1

**Comment by ymxiang1125** [comment]
My solution is to update node version, like 14.21.0 or 16.x.

**Comment by Tianyeeeeee** [comment]
> My solution is to update node version, like 14.21.0 or 16.x.

Thank you, I'll try

**Comment by SprWu** [comment]
> ###Problem: Cannot find module 'node:module' Source code:
> 
> ```js
> const node_ module=require（'node:module'）；// Why is "Node: xxx" added here
> ```
> 
> When I was building the project, I received an error "Cannot find module 'node:module'".
> 
> In my project (Vue3), I used "unplugin vue components" and "unplugin auto import".
> 
> How to solve it?
+1

**Comment by donghainan** [comment]
I resolved this problem by update  node version to v16.18.x
