### ISSUE TITLE
Strip query and hash by `sanitizeURIComponent`

### ISSUE THREAD

**Issue by antfu** [unjs/mlly#138]
### Describe the feature

Related to #137 - Even that PR fixes the bug, it still makes the file name necessarily long. And in practice, if you check the dist of a Nuxt app, you will find there are a lot of files ending with `.vue_vue_type_script_setup_true_lang`:

<img width="665" alt="image" src="https://user-images.githubusercontent.com/11247099/211190395-5188f722-db9f-4a90-a072-605c5eaf0066.png">

Since the bundle already has a hash in the end, the uniqueness shouldn't be a problem.

I would propose to make `sanitizeURIComponent` striping the query and hash directly

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
@antfu Shall we close this?

**Comment by antfu** [comment]
No, it's not #137.

Rather I am asking if you think it's a good idea to strip `?query` and `#hash` for the bundle name (either on mlly or nuxt). 

So `Foo.vue?vue&type=script&setup=true&lang.js` will be generated as:

- `foo.vue.{hash}.js`

instead of the current

- `foo.vue_vue_type_script_setup_true_lang.{hash}.js`

**Comment by pi0** [comment]
Hashing payload (query, hash) seems a really nice idea indeed. Feel free to open PR i can wait for next release.

**Comment by antfu** [comment]
I am more referring to https://github.com/nuxt/framework/blob/c67dbed40755b03cc98497141089a8b54adf06b4/packages/vite/src/vite.ts#L63-L67

Where we use `sanitizeURIComponent` to generate the bundle name. The hash is generated by Rollup already. Do you think the removal of URL query and hash should happen on Nuxt side to keep `sanitizeURIComponent` simple? Or we do another hash here?

**Comment by pi0** [comment]
I think removing it here makes sense as well even with a simple hashing or simply removing anything after `?` altogether. `sanitizeURIComponent` is already a lossy strip function (irreversible removals) and we should as you mention always make sure a hash addition as added to guarantee uniqueness that can happen on nuxt side.

Here we can either strip or use simple hash (like length)
