### ISSUE TITLE
Named default import

### ISSUE THREAD

**Issue by mateenagy** [unjs/mlly#180]
When I use named export like 
```ts
export default useExampleStore;
```
the current check in `findExports` only looking only for `deafult export` in code. This prevent in `unimport` package for example to use `useExampleStore` instead of filename (exampleStore).

I already create a pull request for make it work and also what I did and why:
https://github.com/unjs/mlly/pull/179

Also run all the test with this modification and every test passed.

**Comment by mateenagy** [comment]
Hi @pi0 !
Can you check on this issue if you have some free time? I want to implement some feature in my project which depends on this issue. 

I don't know how relevant this issue, but I think if the `findExport` method extract the name of the export then named default exports should be use the name also and not the file name.

Thank you for your time and for your awesome work and have a nice day!

**Comment by pi0** [comment]
With https://github.com/unjs/mlly/pull/179 new `defaultName` meta allows access to named export variable name
