### ISSUE TITLE
ensure we don't resolve modules in parent folders

### ISSUE THREAD

**Issue by danielroe** [unjs/mlly#200]
Not sure if this is relevant still but opening it here just in case.

https://github.com/nuxt/nuxt/issues/20616#issuecomment-1533727896

**Comment by pi0** [comment]
Thanks for making issue. Yes it is relevant i saw it multiple times but need to make a minimal reproduction (or test fixture) to make sure we don't introduce any side-effect regressions by making this change (however I'm pretty sure with all tests it will break some implicit cases that mlly was working for nested `node_modules` resolution, wrongly-and-correctly!)

**Comment by pi0** [comment]
Let's track in #158
