### ISSUE TITLE
_findSubpath a strange import error 

### ISSUE THREAD

**Issue by productdevbook** [unjs/mlly#209]
### Environment

[Postgress](https://github.com/porsager/postgres/blob/master/package.json)

Node: 20.10.0

### Reproduction

```
https://github.com/porsager/postgres/blob/master/package.json

  "name": "postgres",
  "version": "3.4.3",
  "description": "Fastest full featured PostgreSQL client for Node.js",
  "type": "module",
  "module": "src/index.js",
  "main": "cjs/src/index.js",
  "exports": {
    "types": "./types/index.d.ts",
    "bun": "./src/index.js",
    "worker": "./cf/src/index.js",
    "import": "./src/index.js",
    "default": "./cjs/src/index.js"
  },
  ```

### Describe the bug

`_findSubpath` The func goes and takes it as it first finds it, whereas in the true path there is no such way. 

While testing auth import I saw that this box had a problem there `_findSubpath` 

```
presets: [
            {
              from: 'postgres',
              imports: [
                'PostgresError',
              ],
            },
          ],
```

```
  const PostgresError: typeof import('../../../../../node_modules/.pnpm/postgres@3.4.3/node_modules/postgres/bun')['PostgresError']
  ``` 
  
I don't know what solution we should apply.

**Comment by pi0** [comment]
Would you be able to make a more minimal reproduction or at least clear steps to reproduce? 🙏🏼

**Comment by productdevbook** [comment]
I'll write a test and send it to pr. We will be more comfortable over the test.

**Comment by productdevbook** [comment]
@pi0 https://github.com/unjs/mlly/issues/209 check please, i am add test

**Comment by pi0** [comment]
Thanks! should be fixed in next release
