### ISSUE TITLE
Node 22: `fs.Stats` constructor is deprecated

### ISSUE THREAD

**Issue by RobinTail** [unjs/mlly#246]
For your information, this warning appears when running `vitest` in Node 22 environment:

```
(node:2057) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
```

I managed to figure out that it comes from `mlly` being the dependency of `vitest`:

```
=> Found "mlly@1.6.1"
info Reasons this module exists
   - "vitest#local-pkg" depends on it
   - Hoisted from "vitest#local-pkg#mlly"
   - Hoisted from "vitest#local-pkg#pkg-types#mlly"
```

The exact statement causing the issue is not present in the source code of `mlly`, but is generated in its build/distribution by `rollup`:

![image](https://github.com/unjs/mlly/assets/13189514/c93598f1-e5c4-45e1-a1c9-ffb28ce90fd8)

Consider upgrading `rollup` and its relatives, or adjust the line of code that may lead to that statement in production.

There is also a duplication of `rollup` in your lock file:

https://github.com/unjs/mlly/blob/c282adb509cdb6a96343095504d6feeffd65217b/pnpm-lock.yaml#L2171-L2176

**Comment by srbarba** [comment]
Same problem nuxt:

https://github.com/nuxt/nuxt/issues/26975

**Comment by danielroe** [comment]
This is an upstream issue (https://github.com/wooorm/import-meta-resolve/issues/27) which is resolved in v4.1.0 of `import-meta-resolve`, but because `mlly` inline `import-meta-resolve`, it may take a little while for the fix to percolate downward.

**Comment by pi0** [comment]
Fix already merged via https://github.com/unjs/mlly/pull/249

**Comment by pi0** [comment]
https://github.com/unjs/mlly/releases/tag/v1.7.0

---

For nuxt users, you need a new nuxi release please followup via https://github.com/nuxt/cli/issues/405
